#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔎 Running ESLint..."
npm run lint || exit 1

echo "🎨 Running Prettier check..."
npm run prettier:check || exit 1

echo "🧪 Running tests..."
npm test || exit 1

echo "✅ All checks passed!"
